---
abstract: 'Simple Interface to Yahoo! JAPAN Web APIs'
author:
  - 'AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Simple-Yahoo-JP-API
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  WebService::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
